### ISSUE TITLE
[Feature Request] Add GitHub App user name and email in outputs. 

### ISSUE THREAD

**Issue by huxuan** [actions/create-github-app-token#114]
According to the discussion here: https://github.com/orgs/community/discussions/24664, sometimes, we want to know the GitHub App's user name and user id (for the corresponding email address), it would be great if we can have those in the outputs.

**Comment by gr2m** [comment]
Hi Xuan, we already export `app-slug`, see [outputs](https://github.com/actions/create-github-app-token?tab=readme-ov-file#outputs).

In order to get the user ID of an app, an additional request needs to be sent. As that is not a common enough use case, I suggest we update the README to show how to do it.

Say `outputs.app-slug` is `my-app`, then the user name is `my-app[bot]`. With that you can retrieve the user ID at [`GET /users/{login}`](https://api.github.com/users/my-app%5Bbot%5D).

**Comment by gr2m** [comment]
Actually it might suffice to just do `my-app[bot]@users.noreply.github.com` as the git email, without the need of adding the user ID of the app, can you give that a try?

**Comment by huxuan** [comment]
Great, I will try it soon. Thanks for the information.

**Comment by huxuan** [comment]
It works like a charm! Thanks again and close the issue now.
