### ISSUE TITLE
Release workflow is failing

### ISSUE THREAD

**Issue by gr2m** [actions/create-github-app-token#81]
Build: https://github.com/actions/create-github-app-token/actions/runs/6841698226/job/18603233519

```
✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://x-access-token:[secure]@github.com/actions/create-github-app-token HEAD:main
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: Review all repository rules at http://github.com/actions/create-github-app-token/rules?ref=refs%2Fheads%2Fmain        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
remote: - 2 of 2 required status checks are expected.        
remote: 
```

However, the app that we authenticate with for the semantic-release setup is configured to bypass the rule:

![Image](https://github.com/actions/create-github-app-token/assets/39992/93f2b767-fc18-468f-9dec-a766fe5e1b6e)

So I'm not sure what's up, I'm pretty sure this worked before 🤷

**Comment by parkerbxyz** [comment]
There were branch protection rules that were conflicting with the repository ruleset. 

The error message from the logs was misleading, because the problem was with the branch protection rules, not the repository ruleset linked in the error message. I updated the repository ruleset to match the branch protection rules and then deleted the branch protection rules to resolve the conflict.

The release workflow is working after these changes: https://github.com/actions/create-github-app-token/actions/runs/6841698226/job/18765611377
